spring:
  datasource:
    url: jdbc:mysql://localhost/our_meeting
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect

logging.level:
  org.hibernate.SQL: debug
